---
  - name: restart postfix
    become: True
    service:
      name: "{{ mailclient_postfix_service }}"
      enabled: yes
      state: restarted

  - name: restart krbhelper
    become: True
    service:
      name: postfix-krbhelper.timer
      enabled: yes
      state: restarted

  - name: reload systemd-postfix
    become: True
    service:
      name: "{{ mailclient_postfix_service }}"
      enabled: yes
      state: restarted
      daemon_reload: yes

  - name: reload systemd-krbhelper
    become: True
    service:
      name: postfix-krbhelper.timer
      enabled: yes
      state: restarted
      daemon_reload: yes

  - name: newalias
    become: True
    command: newaliases

  - name: rebuild virtual map
    become: True
    command: postmap /etc/postfix/virtual
    notify:
      - restart postfix

  - name: rebuild sender map
    become: True
    command: postmap /etc/postfix/sender_canonical_maps
    notify:
      - restart postfix

  - name: rebuild sasl map
    become: True
    command: postmap /etc/postfix/sasl_passwd
    notify:
      - restart postfix
